# !!!! This package (xorg-libxcb) has been deprecated in favor of
# `libxcb` for compatibility with Anaconda `defaults` !!!!

{% set xorg_name = "libxcb" %}
{% set xorg_category = "xcb" %}
{% set name = "xorg-" ~ xorg_name %}
{% set version = "1.13" %}
{% set sha256 = "188c8752193c50ff2dbe89db4554c63df2e26a2e47b0fa415a70918b5b851daa" %}
{% set am_version = "1.15" %} # keep synchronized with build.sh

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ xorg_name }}-{{ version }}.tar.bz2
  url: https://www.x.org/releases/individual/{{ xorg_category }}/{{ xorg_name }}-{{ version }}.tar.bz2
  sha256: {{ sha256 }}
  patches:
    - python3.patch
    - windows.patch  # [win]

# NOTE: Python isn't a runtime dependency, but we need to matrix across Python
# versions to cover the different Visual Studio versions.

build:
  skip: true # !!!!!!!
  number: 0
  detect_binary_files_with_prefix: true
  features:
    - vc9  # [win and py27]
    - vc10  # [win and py34]
    - vc14  # [win and py>=35]

requirements:
  build:
    - m2-autoconf  # [win]
    - m2-automake{{ am_version }}  # [win]
    - m2-libtool  # [win]
    - m2w64-pkg-config  # [win]
    - m2w64-toolchain  # [win]
    - pkg-config  # [not win]
    - posix  # [win]
    - python
    - toolchain
    - vc 9  # [win and py27]
    - vc 10  # [win and py34]
    - vc 14  # [win and py>=35]
    - xorg-libpthread-stubs
    - xorg-libxau
    - xorg-libxdmcp
    - xorg-util-macros
    - xorg-xcb-proto
    - xorg-xproto
  run:
    - vc 9  # [win and py27]
    - vc 10  # [win and py34]
    - vc 14  # [win and py>=35]
    - xorg-libpthread-stubs
    - xorg-libxau
    - xorg-libxdmcp

test:
  commands:
    - conda inspect linkages -p $PREFIX $PKG_NAME  # [not win]
    - conda inspect objects -p $PREFIX $PKG_NAME  # [osx]

about:
  home: https://www.x.org/
  license: MIT
  license_family: MIT
  license_file: COPYING
  summary: 'A modernized X protocol transport library.'

extra:
  recipe-maintainers:
    - pkgw
